### ISSUE TITLE
Power factor decimal separator position

### ISSUE THREAD

**Issue by Lonkoding** [alryaz/hass-hekr-component#7]
Hi! Before all, thanks a lot for this project, I can perfectly record the DDS238-4 data from hass.io.

Found the following issue: The power factor seems to be registered divided by 10, one decimal position to the right that it should be.

![imagen](https://user-images.githubusercontent.com/66270695/118362942-5c9dbe00-b568-11eb-8f61-6eba27640bfd.png)

In the image power factor is 0.0888 when it should be 0.888, considering the current, voltage and power at that moment.

**Comment by alryaz** [comment]
Acknowledged; will push a minor commit soon

**Comment by scannifn** [comment]
Hello guys, I confirm the same issue. Should be 0.xxx and not 0.0xxx
In effect in Wisen App is correct

![image](https://user-images.githubusercontent.com/67062892/127126788-c4563f09-ce3c-403f-8bf1-ac5393cb3808.png)


I have firmware 4.2.6.1. @Lonkoding could you check your firmware versione from Wisen App?

**Comment by alryaz** [comment]
@Lonkoding
Release v0.2.9 fixes this issue. Should any relevant bugs arise, please, reopen this issue.
