### ISSUE TITLE
Integration not working after HA Core update 2021.6

### ISSUE THREAD

**Issue by scannifn** [alryaz/hass-hekr-component#8]
Hi, I was using this integration and it was very useful for me. Unfortunatly after the updates of HA (2021.6) the integration was not loaded anymore.

I have this message in notifications:
![image](https://user-images.githubusercontent.com/67062892/121204509-37eeea80-c877-11eb-8678-c0fa4110a18e.png)

Detals in the log:
![image](https://user-images.githubusercontent.com/67062892/121204659-5228c880-c877-11eb-9e7f-2ee29ee0cbee.png)

Please could you give to this integration a new life?
Thanks

**Comment by alryaz** [comment]
Version number bumped, issue related to invalid numbering. Resolved in v0.2.8.
